# Generated by Django 3.2.13 on 2022-06-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sensor1',
            fields=[
                ('timestamp', models.IntegerField(primary_key=True, serialize=False)),
                ('P1', models.FloatField()),
                ('P2', models.FloatField()),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField()),
            ],
            options={
                'db_table': 'sensor1',
            },
        ),
        migrations.CreateModel(
            name='sensorList',
            fields=[
                ('sensorID', models.IntegerField(primary_key=True, serialize=False)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('installDate', models.DateField()),
            ],
            options={
                'db_table': 'sensorList',
            },
        ),
    ]
