# Generated by Django 3.2.13 on 2022-06-02 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airMonitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sensor1',
            table='sensor1',
        ),
        migrations.AlterModelTable(
            name='sensorlist',
            table='sensorList',
        ),
    ]
