# Generated by Django 3.2.13 on 2022-06-14 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airMonitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sensorReading',
            fields=[
                ('uniqueID', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateField()),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField()),
            ],
            options={
                'db_table': 'sensorReading',
            },
        ),
        migrations.DeleteModel(
            name='sensor1',
        ),
        migrations.RemoveField(
            model_name='sensorlist',
            name='installDate',
        ),
        migrations.AddField(
            model_name='sensorlist',
            name='location_id',
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensorlist',
            name='sensorType',
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='sensorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airMonitor.sensorlist'),
        ),
    ]
