# Generated by Django 3.2.13 on 2022-06-14 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airMonitor', '0002_auto_20220614_1530'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sensorReading',
            new_name='DHT22Reading',
        ),
        migrations.AlterModelTable(
            name='dht22reading',
            table='DHT22Reading',
        ),
        migrations.CreateModel(
            name='SDS011Reading',
            fields=[
                ('uniqueID', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateField()),
                ('P1', models.FloatField()),
                ('P2', models.FloatField()),
                ('sensorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airMonitor.sensorlist')),
            ],
            options={
                'db_table': 'SDS011Reading',
            },
        ),
        migrations.CreateModel(
            name='BME280Reading',
            fields=[
                ('uniqueID', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateField()),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField()),
                ('pressure', models.FloatField()),
                ('sensorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airMonitor.sensorlist')),
            ],
            options={
                'db_table': 'BME280Reading',
            },
        ),
    ]
