# Generated by Django 3.2.13 on 2022-06-03 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airMonitor', '0002_auto_20220602_1423'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sensorlist',
            table='sensorlist',
        ),
    ]
