# Generated by Django 3.2.13 on 2022-06-03 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airMonitor', '0003_alter_sensorlist_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sensorlist',
            table='sensorList',
        ),
    ]
