# Generated by Django 3.2.13 on 2022-07-07 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airMonitor', '0004_auto_20220614_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bme280reading',
            options={'verbose_name': 'BME280', 'verbose_name_plural': 'BME280s'},
        ),
        migrations.AlterModelOptions(
            name='dht22reading',
            options={'verbose_name': 'DHT22', 'verbose_name_plural': 'DHT22s'},
        ),
        migrations.AlterModelOptions(
            name='sds011reading',
            options={'verbose_name': 'SDS011', 'verbose_name_plural': 'SDS011s'},
        ),
        migrations.AlterModelOptions(
            name='sensorlist',
            options={'verbose_name': 'SensorList', 'verbose_name_plural': 'SensorLists'},
        ),
    ]
