# Generated by Django 3.2.13 on 2022-07-14 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airMonitor', '0005_auto_20220707_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastSDS011Readings',
            fields=[
                ('uniqueID', models.IntegerField(primary_key=True, serialize=False)),
                ('pastDate', models.DateTimeField()),
                ('dailyAverageP1', models.FloatField()),
                ('dailyAverageP2', models.FloatField()),
                ('sensorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airMonitor.sensorlist')),
            ],
            options={
                'verbose_name': 'PastSDS011',
                'verbose_name_plural': 'PastSDS011s',
                'db_table': 'PastSDS011Readings',
            },
        ),
        migrations.CreateModel(
            name='PastDHT22Readings',
            fields=[
                ('uniqueID', models.IntegerField(primary_key=True, serialize=False)),
                ('pastDate', models.DateTimeField()),
                ('dailyAverageHumidity', models.FloatField()),
                ('dailyAverageTemperature', models.FloatField()),
                ('sensorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airMonitor.sensorlist')),
            ],
            options={
                'verbose_name': 'PastDHT22',
                'verbose_name_plural': 'PastDHT22s',
                'db_table': 'PastDHT22Readings',
            },
        ),
        migrations.CreateModel(
            name='PastBME280Readings',
            fields=[
                ('uniqueID', models.IntegerField(primary_key=True, serialize=False)),
                ('pastDate', models.DateTimeField()),
                ('dailyAverageHumidity', models.FloatField()),
                ('dailyAverageTemperature', models.FloatField()),
                ('dailyAveragePressure', models.FloatField()),
                ('sensorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airMonitor.sensorlist')),
            ],
            options={
                'verbose_name': 'PastBME280',
                'verbose_name_plural': 'PastBME280s',
                'db_table': 'PastBME280Readings',
            },
        ),
    ]
